### ISSUE TITLE
Execution failed for task ':app:processDebugManifest'.

### ISSUE THREAD

**Issue by szgozcan** [EddyVerbruggen/nativescript-admob#67] opened 2019-07-03 08:51 UTC
Hi,
Since yesterday I have been facing the similar issue with all my running and newly created apps.

When I run "tns run android" command I get

    * What went wrong:
    Execution failed for task ':app:processDebugManifest'.
    > Manifest merger failed : Attribute application@appComponentFactory value=   (androidx.core.app.CoreComponentFactory) from [androidx.core:core:1.0.0]    AndroidManifest.xml:22:18-86
            is also present at [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91 value=(android.support.v4.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:17:2-38:16 to override.

I have changed many things in AndroidManifest.xml but none of them have worked. 

I created a blank project and it ran but when I added nativescript-admob I got the same issue.

My environment information:
    No issues were detected.
    ✔ Your ANDROID_HOME environment variable is set and points to correct directory.
    ✔ Your adb from the Android SDK is correctly installed.
    ✔ The Android SDK is installed.
    ✔ A compatible Android SDK for compilation is found.
    ✔ Javac is installed and is configured properly.
    ✔ The Java Development Kit (JDK) is installed and is configured properly.
    ✔ Xcode is installed and is configured properly.
    ✔ xcodeproj is installed and is configured properly.
    ✔ CocoaPods are installed.
    ✔ CocoaPods update is not required.
    ✔ CocoaPods are configured properly.
    ✔ Your current CocoaPods version is newer than 1.0.0.
    ✔ Python installed and configured correctly.
    ✔ The Python 'six' package is found.
    ✔ Xcode version 9.4.1 satisfies minimum required version 9.
    ✔ Getting NativeScript components versions information...
    ⚠ Update available for component nativescript. Your current version is 5.0.0-2018-10-12-12481 and the latest available version is 5.4.2.
   ✔ Component tns-core-modules has 5.4.3 version and is up to date.
   ✔ Component tns-android has 5.4.0 version and is up to date.
   ✔ Component tns-ios has 5.4.2 version and is up to date.

**Comment by szgozcan** [comment] 2019-07-03 08:53
I think the problem might be related to nativescript-admob plugin

**Comment by szgozcan** [comment] 2019-07-03 08:56
And when I remove nativescript-admob plugin app runs again

**Comment by surdu** [comment] 2019-07-15 00:16
I have the same the same issue. I tried downgrading `nativescript-admob` down to v3.2.0, but the problem still persists.

@szgozcan Do you remember changing something to your project before the problem started showing ? Maybe upgrading something ?

**Comment by Djip** [comment] 2019-07-15 08:51
Having the exact same issue, @EddyVerbruggen are you going to fix this sooner or later?

**Comment by EddyVerbruggen** [comment] 2019-07-15 10:35
@Djip Is that a trick question?

**Comment by Djip** [comment] 2019-07-15 10:37
@EddyVerbruggen No sorry, not meant that way. Actually wanted to ask for an ETA, since it isn't working with the latest Nativescript

**Comment by EddyVerbruggen** [comment] 2019-07-15 10:40
Haha, no worries. I was kidding. I was actually just taking a look today. Hopefully, I can reproduce it and sort it out.

**Comment by EddyVerbruggen** [comment] 2019-07-15 11:52
So it turns out there's an issue since Google Play Services (Ads) 18 (released in June) or 18.1 (released in July).

The plugin used version `+` until release 3.3.3 (which is now on npm). We're now pinning to `17+` until a better solution pops up.

You'll have to remove your `platforms` folder after bumping the plugin version to make sure this change sticks.

**Closed by EddyVerbruggen** 2019-07-15 11:52 UTC
Labels: Android, bug
