### ISSUE TITLE
Suggestion: preload Interstitial

### ISSUE THREAD

**Issue by calebeaires** [EddyVerbruggen/nativescript-admob#3] opened 2016-03-18 19:18 UTC
Admob team contact me about policy from interstital implementation. They suggest to preload the ad first (ex: when app starts), then show on needed.

This is useful to "Rewarded mediation": https://support.google.com/admob/answer/3063564?hl=en

I have did some modification. It is not the final implementation, but It is a start.

```
admob.preloadInterstitial = function(arg) {
  return new Promise(function (resolve, reject) {
    try {
      var settings = admob.merge(arg, admob.defaults);
      var activity = application.android.foregroundActivity;
      admob.interstitialView = new com.google.android.gms.ads.InterstitialAd(activity);
      admob.interstitialView.setAdUnitId(settings.androidInterstitialId);

      // Interstitial ads must be loaded before they can be shown, so adding a listener
      var InterstitialAdListener = com.google.android.gms.ads.AdListener.extend({
        onAdLoaded: function () {
          var a = admob.interstitialView.isLoaded();
          resolve(a);
        },
        onAdFailedToLoad: function (errorCode) {
          reject(errorCode);
        }
      });
      admob.interstitialView.setAdListener(new InterstitialAdListener());

      var ad = admob._buildAdRequest(settings);
      admob.interstitialView.loadAd(ad);

    } catch (ex) {
      console.log("Error in admob.createBanner: " + ex);
      reject(ex);
    }
  });
};
```

**Comment by SteveOliverC** [comment] 2017-09-02 13:35
This should be more than a suggestion, because using the plugin this way is a violation of Admob's policies and as the OP says they will contact you. It is within Admob's rights to withhold your ad money and terminate your account. The issue is that they specifically say you cannot show an interstitial an indeterminate amount of time after the action that triggered it. It will almost never be the case that the interstitial is loaded immediately after it is requested. The way this plugin works at the moment, it will nearly always present the interstitial a few seconds after you call it, and that is exactly what Admob does not allow.

**Comment by EddyVerbruggen** [comment] 2017-09-02 13:55
That's clear. Anyone wanting to contribute a solution?

**Comment by tscislo** [comment] 2018-03-21 20:04
Any update on this?

**Comment by umair-ameen** [comment] 2018-07-11 13:35
Any update about it?

**Comment by skopekreep** [comment] 2018-09-10 21:53
In the README, it says: "**Note that Interstitial banners need to be loaded before they can be shown, but don't worry: this plugin will manage that transparently for you**", which seems in contradiction to this (open) issue.  Can you please clarify if preloading has been added for both platforms and this issue should be closed, or if the above statement is incomplete or inaccurate?

**Comment by EddyVerbruggen** [comment] 2018-09-11 05:28
It’s accurate AND preloading hasn’t been added but it’s still up for grabs.

What the readme says is you don’t have to call 2 functions (load, then show when loaded) as it’s all integrated into 1 function.

**Comment by sayeed360** [comment] 2018-09-13 16:36
> 
> 
> It’s accurate AND preloading hasn’t been added but it’s still up for grabs.
> 
> What the readme says is you don’t have to call 2 functions (load, then show when loaded) as it’s all integrated into 1 function.

Can you please provide an example. All I can see is when I use your example on the main readme, it shows the ad as soon as it is loaded. How do I preload the ad and show when needed?

**Comment by SteveOliverC** [comment] 2018-09-13 17:09
You are using a test ad, so that displays very quickly. But a normal ad will take at least a few seconds to load, and maybe longer depending on the ad content and the device connection. The way to test this properly is to log to the console when the ad is successfully loaded (or not), and then trigger the ad to display based on some action by the user. And this cannot be done with the plugin as it currently is.

**Comment by sayeed360** [comment] 2018-09-13 17:15
So any other alternatives? maybe another plugin? How do you guys solve this problem in your own apps?

**Comment by EddyVerbruggen** [comment] 2018-09-13 18:28
Exactly as @SteveOliverC states.

Btw, it's not too hard to add to this plugin, it's just a matter of priority/time.

**Comment by mimamo10** [comment] 2018-09-27 11:20
Thanks for the plugin, really appreciate it.  But as it stands we shouldn't use the plugin for interstitial ads without first hacking the plugin code?

**_"Note that Interstitial banners need to be loaded before they can be shown, but don't worry: this plugin will manage that transparently for you."_** gives an entirely different impression!

SteveOliverC says he couldn't figure it out, so fat chance for those of us with lesser skills.

**Comment by mimamo10** [comment] 2018-09-27 12:39
Okay, I see.  We can't preload and show when needed, but it effectively preloads.  Hacking only needed if we want to show the ad at a later point from when it's loaded.

**Comment by EddyVerbruggen** [comment] 2018-09-27 12:58
Yep, that’s what that quote tries to say.

**Comment by EddyVerbruggen** [comment] 2018-09-28 20:05
Let me try to be clear:

- Yes, there's an issue (we need to add a function to explicitly load interstitials). At the moment they are preloaded automatically and shown when loaded (which allegedly is frowned upon by Google), instead of preloaded and shown on demand.
- No, nothing was changed / fixed yet.
- Happy to merge a PR because this issue needs to fight for my time with literally hundreds of other issues.

**Comment by EddyVerbruggen** [comment] 2018-09-29 15:51
FYI I'm spending my weekend fixing this. iOS is already done. Android tomorrow. There will be 2 new methods: `preloadInterstitial` (with the same parameters as the current `createInterstitial`), and `showInterstitial` which should not be called before the promise of `preloadInterstitial` resolves, but _can_ be called a long time after it has been preloaded.

**Comment by umair-ameen** [comment] 2018-09-30 05:43
Is it fixed in nativescript-plugin-firebase as well?

**Comment by EddyVerbruggen** [comment] 2018-09-30 07:51
2.0.0 released, see [the updated docs](https://github.com/EddyVerbruggen/nativescript-admob/tree/c780dacbcab3bf71aa9c59f1763fcbb7d996e196#interstitial).

**Closed by EddyVerbruggen** 2018-09-30 07:51 UTC
Labels: Android, enhancement, help wanted, iOS

**Comment by EddyVerbruggen** [comment] 2018-09-30 14:44
@umair-ameen Check https://github.com/EddyVerbruggen/nativescript-plugin-firebase/issues/934 - now available from npm in nativescript-plugin-firebase version 7.1.1.

**Comment by umair-ameen** [comment] 2018-10-01 12:32
@EddyVerbruggen Thank you so much Eddy. You are awesome.

**Comment by SteveOliverC** [comment] 2018-10-01 14:14
@EddyVerbruggen NICE work!!!

**Comment by mimamo10** [comment] 2018-10-02 12:41
Brilliant, thanks!
